apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-g-az
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-g-az 
  name: test-g-az
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: test-g-az 
